/* ScummVM - Graphic Adventure Engine
 *
 * ScummVM is the legal property of its developers, whose names
 * are too numerous to list here. Please refer to the COPYRIGHT
 * file distributed with this source distribution.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef SHERLOCK_NARRATOR_AUDIO_H
#define SHERLOCK_NARRATOR_AUDIO_H

#include "common/hashmap.h"
#include "common/hash-str.h"
#include "common/path.h"
#include "common/str.h"

namespace Sherlock {

class SherlockEngine;

/**
 * Loads and indexes narrator-VO audio assets shipped under the game
 * directory's `narrator_audio/` subdirectory.
 *
 * **Phase 3.2 status: skeleton class.** Manifest loader + lookup helpers
 * only — no playback wiring yet. Subsequent sub-phases connect the lookup
 * to engine call sites:
 *   - 3.4: object_examine + inventory_description hooks
 *   - 3.5: journal scene-titles + connective phrases
 *   - 3.6: hotspot_description action-failure fallbacks
 *
 * Manifest format: a JSON array of objects, each with `{id, text,
 * voice_role, category, ...}`. Generated by the parent project's
 * `tools/extract_narrator_text/` pipeline; deployed to
 * `<gamedir>/narrator_audio/manifest.json` by the parent's
 * `tools/deploy_narrator_audio.py`. Audio files live alongside the
 * manifest as `<entry_id>.mp3` (MP3 44.1 kHz 192 kbps mono).
 *
 * `%s`-templated Watson connectives (6 entries) are present in the
 * manifest but excluded from the lookup map at load time — they have no
 * audio file by design (the `%s` is a runtime NPC-name substitution).
 * Engine-side handling of those rows (silent rendering for v0.6.0,
 * per the Phase 3 plan) happens at the call site, not here.
 */
class NarratorAudio {
public:
	enum VoiceRole {
		kRoleUnknown  = 0,
		kRoleNarrator = 1,
		kRoleWatson   = 2
	};

	struct Entry {
		VoiceRole role;
		Common::String filename;  // "<id>.mp3" relative to narrator_audio/
	};

	NarratorAudio(SherlockEngine *vm);
	~NarratorAudio();

	/**
	 * Open `<gamedir>/narrator_audio/manifest.json`, parse it as a JSON
	 * array of entries, and populate the lookup map with every non-`%s`
	 * row whose audio file is present alongside the manifest.
	 *
	 * Returns true if the file was opened, parsed, and at least one
	 * entry was added to the map. Returns false (and leaves the map
	 * empty) if any of those steps fail. Logs the entry count via
	 * `debug()`; logs failures via `warning()`. Safe to call once;
	 * re-calling is a no-op (returns the cached result).
	 */
	bool load();

	/** True iff load() ran and produced a non-empty entry map. */
	bool isLoaded() const { return _loaded; }

	/**
	 * Number of entries in the lookup map. Excludes the 6 `%s`
	 * placeholder rows that don't have audio.
	 */
	uint32 entryCount() const { return _entries.size(); }

	/**
	 * Look up an entry's audio file path relative to the game
	 * directory (e.g. `narrator_audio/scalpel_r17_obj01_examine.mp3`).
	 * Returns an empty Path if the entry isn't in the map.
	 */
	Common::Path lookupAudioPath(const Common::String &entryId) const;

	/** Look up an entry's voice role. Returns kRoleUnknown if not in map. */
	VoiceRole lookupVoiceRole(const Common::String &entryId) const;

	/** True iff `entryId` is in the lookup map. */
	bool hasEntry(const Common::String &entryId) const {
		return _entries.contains(entryId);
	}

private:
	SherlockEngine *_vm;
	bool _loaded;
	Common::HashMap<Common::String, Entry> _entries;
};

} // End of namespace Sherlock

#endif
